### ISSUE TITLE
add a time stamp

### ISSUE THREAD

**Issue by ooohfasinating** [DestinyTheGame/gorgon.exchange#1]
You  should add on a time stamp so we know when the checkpoint was added. That way we dont get excited about a post only to find out it was posted yesterday

**Comment by jeromegn** [comment]
Yes, please add a timestamp :)

**Comment by 3rd-Eden** [comment]
Timestamps added with 0ac4664ce0457138338304cefaabd0fc7d3c4df3 and currently live on gorgon.exchange. Thanks for raising the issue.
