### ISSUE TITLE
Sorting and filtering

### ISSUE THREAD

**Issue by jeromegn** [DestinyTheGame/gorgon.exchange#2]
It would be nice to be able to filter by console.

And maybe sort by time / comments count / votes, etc. Time is the most important to be honest, a default of most recent to least recent would work for my use.

This is just a feature request, good job!

**Comment by 3rd-Eden** [comment]
Filtering is added. Sorting is not something I'm going to implement as the fresh posts will be the most interesting. They are currently flagged as old if they are older then 4 hours (see #8) and have not been removed automatically by the algorithm.
